"""Initial migration after reset

Revision ID: 1a2c314bd005
Revises: 
Create Date: 2024-03-26 08:32:26.893137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1a2c314bd005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_report_month')
    op.drop_table('meter_reading_issue')
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.alter_column('device_number',
               existing_type=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.alter_column('device_number',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    op.create_table('meter_reading_issue',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('meter_reading_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('resolved', mssql.BIT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK__meter_rea__user___17F790F9'),
    sa.PrimaryKeyConstraint('id', name='PK__meter_re__3213E83FA956B9ED')
    )
    op.create_table('user_report_month',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK__user_repo__user___29221CFB'),
    sa.PrimaryKeyConstraint('id', name='PK__user_rep__3213E83F5472E8BF')
    )
    # ### end Alembic commands ###
