"""dodano pole do modelu usera delta

Revision ID: 7ba872f09d4f
Revises: 1a2c314bd005
Create Date: 2024-03-28 14:15:57.346262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba872f09d4f'
down_revision = '1a2c314bd005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_delta', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_view_delta')

    # ### end Alembic commands ###
